# Cloudflare Pages build configuration
# https://developers.cloudflare.com/workers/platform/compatibility-dates/

pages_build_output_dir = ".next/static"

[env.production]
compatibility_date = "2026-08-15"
compatibility_flags = ["nodejs_compat"]

